name: CI

on:
  release:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  release:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: https://registry.npmjs.org

      - name: publish
        run: npm publish --access public
        env: 
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
